#!/usr/bin/env node
/**
 * Deterministic canonical reconciliation CLI (Pilot 05).
 *
 * Reads the four committed normalized sources
 *   data/sps/sp-s-29-2025.json
 *   data/peakbagger/lid-5051.json
 *   data/peakbagger/cid-30050.json
 *   data/crosswalk.json
 * reconciles them against the frozen data contract (docs/data-contract.md
 * §2/§5/§8) via src/data/reconcile.ts, and writes:
 *   data/reconciled.json              canonical 247-peak active dataset
 *   docs/reconciliation-report.md     machine-generated reconciliation report
 *
 * Usage:
 *   node scripts/reconcile/reconcile.mjs            # import (write both outputs)
 *   node scripts/reconcile/reconcile.mjs --dry-run  # verify + print summary/diff, write nothing
 *   node scripts/reconcile/reconcile.mjs --check    # verify; exit 1 if committed outputs would drift
 *
 * Determinism: each output is a pure function of (committed source data,
 * parser version, report timestamp). The report timestamp is pinned to the
 * Peakbagger snapshot retrieval date, not wall-clock time, so committed
 * outputs are byte-reproducible. CI runs --check so committed data that the
 * reconciler cannot reproduce byte-for-byte fails the build (frozen §5 step 4).
 *
 * This is an offline tool: it never fetches anything from the network.
 */
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

import { reconcile, reconcileToJson } from '../../src/data/reconcile.ts';

const PARSER_VERSION = '1.0.0';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const SPS_DATA_REL = 'data/sps/sp-s-29-2025.json';
const LID_DATA_REL = 'data/peakbagger/lid-5051.json';
const CID_DATA_REL = 'data/peakbagger/cid-30050.json';
const XWALK_DATA_REL = 'data/crosswalk.json';
const OUTPUT_REL = 'data/reconciled.json';
const REPORT_REL = 'docs/reconciliation-report.md';

function fail(message) {
  console.error(`Reconciliation FAILED: ${message}`);
  process.exit(1);
}

function loadJson(rel) {
  const abs = path.join(ROOT, rel);
  if (!existsSync(abs)) fail(`missing committed source: ${rel}`);
  try {
    return JSON.parse(readFileSync(abs, 'utf8'));
  } catch (err) {
    fail(`invalid JSON in ${rel}: ${err.message}`);
  }
}

function sha256OfFile(absPath) {
  return createHash('sha256').update(readFileSync(absPath)).digest('hex');
}

function buildReport(result, parserVersion, snapshotDate) {
  const { counts, peaks, collisionFamilies } = result;
  const lines = [];
  lines.push('# Canonical Dataset Reconciliation Report');
  lines.push('');
  lines.push('> Machine-generated by `scripts/reconcile/reconcile.mjs` (parser v' + parserVersion + ').');
  lines.push('> Do not edit by hand; regenerate via the import workflow. See `docs/data-contract.md` §2/§5/§8.');
  lines.push('');
  lines.push('## Sources');
  lines.push('');
  lines.push('| Source | Path | Rows | Role |');
  lines.push('| --- | --- | --- | --- |');
  lines.push('| SPS 29th Edition (Jan 2025) | `data/sps/sp-s-29-2025.json` | ' + counts.sps_total + ' (' + counts.sps_active + ' active + ' + counts.sps_suspended + ' suspended) | canonical id + raw SPS fields |');
  lines.push('| Peakbagger lid=5051 | `data/peakbagger/lid-5051.json` | ' + counts.peakbagger_rows + ' | list order + PB fields |');
  lines.push('| Peakbagger cid=30050 | `data/peakbagger/cid-30050.json` | ' + counts.completions + ' completions | owner public ascents |');
  lines.push('| Crosswalk | `data/crosswalk.json` | ' + counts.crosswalk_entries + ' entries | explicit 1:1 SPS↔PB join |');
  lines.push('');
  lines.push('Snapshot retrieval date: ' + snapshotDate + ' (from data/manifest.json).');
  lines.push('');
  lines.push('## Result');
  lines.push('');
  lines.push('- Canonical active dataset: **exactly ' + counts.canonical_active + ' peaks** (`data/reconciled.json`).');
  lines.push('- Suspended Pilot Knob (spk-1.1, SPS 1.1) is retained in source data and excluded from the active dataset.');
  lines.push('- Every active Peakbagger row maps exactly once; every completion resolves to an active canonical id.');
  lines.push('- N/S name collisions resolved by SPS section id + order; no name-only joins.');
  lines.push('- No duplicates, no missing canonical rows, no unknown completion references, no sample/mock dates.');
  lines.push('');
  lines.push('## N/S collision families (resolved by section id)');
  lines.push('');
  lines.push('| Family | Canonical ids |');
  lines.push('| --- | --- |');
  for (const [family, ids] of Object.entries(collisionFamilies)) {
    lines.push('| ' + family + ' | ' + (ids.length ? ids.join(', ') : 'none active (suspended)') + ' |');
  }
  lines.push('');
  lines.push('## Per-peak reconciliation');
  lines.push('');
  lines.push('| spk id | SPS name | SPS class | PB order | PB id | PB name | Completed | Date |');
  lines.push('| --- | --- | --- | --- | --- | --- | --- | --- |');
  for (const p of peaks) {
    const done = p.completion ? 'yes' : 'no';
    const date = p.completion ? p.completion.date + (p.completion.day_suffix ? ' ' + p.completion.day_suffix : '') : '—';
    lines.push('| ' + p.sps_id + ' | ' + p.sps_name + ' | ' + p.sps_class_raw + ' | ' + p.pb_order + ' | ' + p.pb_id + ' | ' + p.pb_name + ' | ' + done + ' | ' + date + ' |');
  }
  lines.push('');
  return lines.join('\n');
}

function unifiedDiff(a, b, maxLines = 400) {
  const al = a.split('\n');
  const bl = b.split('\n');
  const out = [];
  const max = Math.max(al.length, bl.length);
  let changed = 0;
  for (let i = 0; i < max; i += 1) {
    const la = al[i];
    const lb = bl[i];
    if (la === lb) {
      out.push(` ${la ?? ''}`);
      continue;
    }
    changed += 1;
    if (la !== undefined) out.push(`-${la}`);
    if (lb !== undefined) out.push(`+${lb}`);
  }
  if (out.length > maxLines) {
    out.push(`... (${out.length - maxLines} more diff lines)`);
    out.length = maxLines;
  }
  if (changed === 0) out.push('(no changes)');
  return out.join('\n');
}

function main() {
  const args = new Set(process.argv.slice(2));
  if (args.size > 1) fail(`unsupported combination of flags: ${[...args].join(' ')}`);
  const mode = args.has('--dry-run') ? 'dry-run' : args.has('--check') ? 'check' : 'import';

  const sps = loadJson(SPS_DATA_REL);
  const lid = loadJson(LID_DATA_REL);
  const cid = loadJson(CID_DATA_REL);
  const xwalk = loadJson(XWALK_DATA_REL);

  // Pin the report timestamp to the Peakbagger snapshot retrieval date so the
  // committed report is byte-reproducible (deterministic).
  const manifest = loadJson('data/manifest.json');
  const snapshotDate = manifest?.sources?.peakbagger?.['lid-5051']?.retrieved_at ?? 'unknown';

  const result = reconcile({
    spsRows: sps.rows,
    spsAreas: sps.areas,
    lidRows: lid.rows,
    cidCompletions: cid.completions,
    crosswalk: xwalk.entries,
  });
  if (!result.ok) {
    fail(`reconciliation failed:\n${result.errors.map((e) => `  - ${e}`).join('\n')}`);
  }

  const outText = reconcileToJson(result, PARSER_VERSION);
  const reportText = buildReport(result, PARSER_VERSION, snapshotDate);

  console.log(`[reconcile ${mode}] canonical reconciler v${PARSER_VERSION}`);
  console.log(`  SPS rows=${result.counts.sps_total} (active=${result.counts.sps_active} suspended=${result.counts.sps_suspended})`);
  console.log(`  Peakbagger rows=${result.counts.peakbagger_rows} crosswalk=${result.counts.crosswalk_entries} completions=${result.counts.completions}`);
  console.log(`  canonical active dataset=${result.counts.canonical_active} peaks`);

  const outputs = [
    [OUTPUT_REL, outText],
    [REPORT_REL, reportText],
  ];

  if (mode === 'import') {
    for (const [rel, out] of outputs) {
      const abs = path.join(ROOT, rel);
      mkdirSync(path.dirname(abs), { recursive: true });
      writeFileSync(abs, out);
      console.log(`  wrote ${rel} sha256 ${sha256OfFile(abs)}`);
    }
    return;
  }

  let anyChange = false;
  for (const [rel, out] of outputs) {
    const existing = existsSync(path.join(ROOT, rel)) ? readFileSync(path.join(ROOT, rel), 'utf8') : null;
    if (existing === null) {
      console.log(`  ${mode}: would CREATE ${rel} — nothing written`);
      anyChange = true;
    } else if (existing === out) {
      console.log(`  ${mode}: ${rel} is up to date (reproduces byte-for-byte) — nothing written`);
    } else {
      anyChange = true;
      console.log(`  ${mode}: ${rel} would CHANGE — nothing written:\n`);
      console.log(unifiedDiff(existing, out));
    }
  }
  if (mode === 'check' && anyChange) {
    fail('committed reconciliation outputs do not reproduce from committed sources (drift)');
  }
}

main();
